version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: restdown-nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./docker/php
    container_name: restdown-php
    restart: unless-stopped
    volumes:
      - .:/var/www/html